In [1]:
print("hello NumPy")

hello NumPy


In [ ]:
# NumPy (Numerical Python) is a core Python library used for fast
# numerical computing, especially with arrays, matrices, and mathematical 
# operations.

# Why NumPy?

# Much faster than Python lists

# Supports multi-dimensional arrays

# Useful for DSA, ML, AI, data science, scientific computing

3️⃣ Array Properties
a.shape      # dimensions
a.size       # total elements
a.dtype      # data type
a.ndim       # number of dimensions

4️⃣ Creating Special Arrays
np.zeros((2,3))   # all elmnts zero
np.ones((3,3))  # all elmnts one
np.eye(3)              # identity matrix
np.arange(0, 10, 2)
np.linspace(0, 1, 5)

7️⃣ Common Functions
np.sum(a)
np.mean(a)
np.max(a)
np.min(a)
np.sqrt(a)

8️⃣ Reshape   # create matrix
a = np.array([1,2,3,4,5,6])
a.reshape(2,3)


SyntaxError: invalid character '️' (U+FE0F) (1817011207.py, line 13)

In [5]:
import numpy as np
var = np.array([1,3,5,6,7,4])
print(var)
print(type(var))     #properties to find  data type

# vector or 1D

[1 3 5 6 7 4]
<class 'numpy.ndarray'>


In [6]:
# 2D matrix
d = np.array([[1,2,3],[4,5,6]])
print(d)
print("shape : ",np.shape(d))   #properties to find rows*colums
d.itemsize    # each integer elements takes 8 bit size in memory for 64bit and 32bit me integer take 4 bits



[[1 2 3]
 [4 5 6]]
shape :  (2, 3)


8

In [7]:
# 3D or tensor
# np.array(layer , rows, cols)
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)
np.ndim(c)      # properties of find diamensions
print("total elements : ",np.size(c))     # properties of find total elements

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
total elements :  8


In [8]:
# dtype    -> convert the data type
np.array([1,2,3,4], dtype = float)         #float/bool/int/complex/char

array([1., 2., 3., 4.])

In [7]:
# np.arange(start,stop, step)    -> range == arange

np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [8]:
# reshape 

# np.arange(1,10).reshape(3,3)
# np.arange(1,13).reshape(3,4)
np.arange(1,11).reshape(5,2)
# np.arange(1,11).reshape(2,5)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [9]:
# zeros    -> 
np.zeros((2,3), dtype =int)      #consider elements bydefault float 

array([[0, 0, 0],
       [0, 0, 0]])

In [10]:
# ones   -> 
np.ones((2,3), dtype =int)      #consider elements bydefault float 

array([[1, 1, 1],
       [1, 1, 1]])

In [ ]:
# pick random number between 0 to 1
np.random.random((3,2))

array([[0.48884967, 0.55247829],
       [0.21759193, 0.02277129],
       [0.49659054, 0.06202347]])

In [12]:
# np.linspace(lower, Upper,numOf elements)  -> equal difference each two elements 

np.linspace(-2,10,10)

array([-2.        , -0.66666667,  0.66666667,  2.        ,  3.33333333,
        4.66666667,  6.        ,  7.33333333,  8.66666667, 10.        ])

In [13]:
# identity matrix -> diagonal elements 1 and rest are zeros
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# scalar operations  -> ek numpy array ke bich me operation hota h 
# arithmetic operations
a = np.array([1,2,3,4])      
print("power : ",a**2)    # for loop lagane ki jarurt nhi this is feature of numpy
print("sum : ",a+2)

power :  [ 1  4  9 16]
sum :  [3 4 5 6]


In [ ]:
# scalar operations  -> ek numpy array ke bich me operation hota h 

# vector operations -> do numpy array e bich me operation hota h
# arithmetics operations
a = np.array([1,2,3])
b = np.array([4,5,6])

print("sum: ",(a + b))
print("multiply : ",(a * 2))



sum:  [5 7 9]
multiply :  [2 4 6]


In [10]:
# relational operations
a = np.array([1,2,3])
a>=2

array([False,  True,  True])

In [17]:
# Array Functions , max,min , mean, avg
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1
                      


array([[30.,  5., 26.],
       [40., 12.,  5.],
       [43., 12., 54.]])

In [18]:
# max find each rows and min 
#axis = 0 for col, and  axis = 1 for rows

print("rows wise max : ",np.max(a1, axis =1))
print("cols wise max : ",np.max(a1, axis =0))
np.min(a1, axis = 1)
print("cols wise sum : ",np.sum(a1, axis =0))
print("rows wise product : ",np.prod(a1, axis =1))


rows wise max :  [30. 40. 54.]
cols wise max :  [43. 12. 54.]
cols wise sum :  [113.  29.  85.]
rows wise product :  [ 3900.  2400. 27864.]


In [19]:
# find mean/median/std/var

print("cols wise mean: ",np.mean(a1,axis = 0))
print("rows wise mean: ",np.mean(a1,axis = 1))
print("rows wise variance: ",np.var(a1,axis = 1))
print("rows wise standard deviation: ",np.std(a1,axis = 1))



cols wise mean:  [37.66666667  9.66666667 28.33333333]
rows wise mean:  [20.33333333 19.         36.33333333]
rows wise variance:  [120.22222222 228.66666667 316.22222222]
rows wise standard deviation:  [10.96458947 15.1217283  17.78263822]


In [20]:
# dot product
v1 = np.arange(6).reshape(2,3)
v2 = np.arange(6).reshape(3,2)
np.dot(v1,v2)


array([[10, 13],
       [28, 40]])

In [ ]:
# calculate log , exponents
a = np.arange(1,5)
print(np.log(a))
np.exp(v1)

[0.         0.69314718 1.09861229 1.38629436]


array([[  1.        ,   2.71828183,   7.3890561 ],
       [ 20.08553692,  54.59815003, 148.4131591 ]])

In [22]:
# round/floor/ceil
a = np.random.random((2,3))*100
print(a,"\n")
print("round: " ,np.round(a))    #1.59 = 2 hoga and 1.49 = 1 hoga (.5 =< se bada h to round me 1 consider karega  
print("floor: ",np.floor(a))     #cosider the left value only mean before decimal
print("ceil: ",np.ceil(a))        #1. 59 = 2 , 1.03 = 2 mean decimal hai to one add kar do


[[79.37061518 58.31073229 61.06331361]
 [91.51556133 63.35616659 42.96174207]] 

round:  [[79. 58. 61.]
 [92. 63. 43.]]
floor:  [[79. 58. 61.]
 [91. 63. 42.]]
ceil:  [[80. 59. 62.]
 [92. 64. 43.]]


In [ ]:
# indexing and slicing
a1 = np.arange(10) # 1D
a2 = np.arange(6).reshape(2,3)  # 2D
a3 = np.arange(8).reshape(2,2,2)  #3D
print(a1)
print(a2)
print(a3)


[0 1 2 3 4 5 6 7 8 9]
[[0 1 2]
 [3 4 5]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [24]:
# find element in 1D
a[1]

array([91.51556133, 63.35616659, 42.96174207])

In [25]:
# 2D
print(a2[1,2])

5


In [26]:
# 3D
# a3[layer, row, col]
print(a3[1,0,0])



4


In [43]:
#2D
arr = np.arange(9).reshape(3,3)
print(arr)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [44]:
# usnig slicing for specific rows or colums or specific numbers only
arr[0,:]     #first row me all colums chaiye read like this

array([0, 1, 2])

In [46]:
arr[:,1]   # all row ka 1st colums

array([1, 4, 7])

In [59]:
arr[1:,1:,]    # 1st(index)/2nd rows se end row tak ke 1st(index)/2nd colums se sab

array([[4, 5],
       [7, 8]])

In [50]:
arr[::2,::2]    # all rows me ek leave karke and all colums me ek leave karke

array([[0, 2],
       [6, 8]])

In [60]:
arr[1::2,1::2]     # 2nd rows se end but one ka gap and 2nd colm ka sab but one ka gap

array([[4]])

In [61]:
# 3D-> slicing using in 3D
a = np.arange(27).reshape(3,3,3)
print(a)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [63]:
a[1::2]    #only layer 1 ka all elements

array([[[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [69]:
a[0,1,:]    # 1st laywer 2nd rows ke sare elmnts

array([3, 4, 5])

In [70]:
a[1,:,1]      #2nd laywer ka sare rows ke 2nd colms only

array([10, 13, 16])

In [74]:
a[2,1:,1:]   # 3rd laywer ke 2nd rows se sab kuch and 2nd colms se sab kuch

array([[22, 23],
       [25, 26]])

In [75]:
a[::2,0,::2]    # 1st and 3rd laywer ka 1st rows wala ke alternate 

array([[ 0,  2],
       [18, 20]])

In [77]:
a[1::2,1,1::2]   #centre only

array([[13]])

In [ ]:
# iterting